[workspace]
members = [
    "client",
    "server"
]

[workspace.dependencies]
futures-util = "0.3.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.25", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
